site_name: Delete Untagged Images Action
site_author: Tristan Nolde
repo_url: https://github.com/TrisNol/delete-untagged-images
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: "README.md"
  - License: "LICENSE.md"

plugins:
  - search
  - mkdocstrings
